articles/urls.py
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    )
from django.urls import path, reverse_lazy, reverse
from . import views

app_name = 'articles'

urlpatterns = [
    path('about_us/', views.AboutusPageView.as_view(), name='about_us'),
    # news in french language
    path('newsapi/', views.newsapi, name='newsapi'),
    path('articles/', views.articles, name='articles'),
    # articles
    path('', views.index, name='index'),
    path('single/<slug:slug>', views.ArticleDetailView.as_view(), name='single_article'),
    path('single/<slug:slug>/update', views.ArticleUpdateView.as_view(), name='update_article'),
    path('single/<slug:slug>/delete', views.ArticleDeleteView.as_view(), name='delete_article'),
    path('create/', views.ArticleCreateView.as_view(), name='create_article'),
    # register, login, logout and password reset 
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

newsapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='index')),
    # password reset
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Article(models.Model):
    HEALTH = 'HL'
    ACTUALITY = 'ACT'
    SPORT = 'SP'
    POLITICS = 'POL'
    BUSINESS = 'BNS'
    ENTERTAINMENT = 'ENTM'
    HISTORY = 'HS'
    LITERATURE = 'LTR'
    CATEGORY_ARTICLE_CHOICES = [
        (HEALTH, 'Health'),
        (ACTUALITY, 'Actuality'),
        (SPORT, 'Sport'),
        (POLITICS, 'Politics'),
        (ENTERTAINMENT, 'Entertainment'),
        (HISTORY, 'History'),
        (LITERATURE, 'Literature'),
    ]
    category = models.CharField(
        max_length=4,
        choices=CATEGORY_ARTICLE_CHOICES,
        default=ACTUALITY,
    )
    title = models.CharField(max_length=1024)
    authors = models.CharField(max_length=1024)
    content = models.TextField()
    authors_image = models.ImageField(upload_to='images/', max_length=100, null=True, blank=True)
    content_image = models.ImageField(upload_to='images/', max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    # updated = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=1024, null=True, blank=True)


    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return self.title

    def is_upperclass(self):
        return self.category in {self.ACTUALITY, self.LITERATURE}
    
    # view author image
    @property
    def authors_image_url(self):
        if self.authors_image and hasattr(self.authors_image, 'url'):
            return self.authors_image.url
        else:
            return "/static/img/authors_default_image.jpg"

    # view content image
    @property
    def content_image_url(self):
        if self.content_image and hasattr(self.content_image, 'url'):
            return self.content_image.url
        else:
            return "/static/img/content_default_image.jpg"
    
    # delete image files
    def delete(self, *args, **kwargs):
        self.authors_image.delete()
        self.content_image.delete()
        super().delete(*args, **kwargs)

articles/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.forms import fields
from .models import Article

User = get_user_model()

class ArticleModelForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = (
            'category',
            'title',
            'authors',
            'content',
            'authors_image',
            'content_image',
            'slug',
        )

class CustomCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            )
        field_classes = {
            'username': UsernameField,
            }
# create, update and delete if staff
class SignupAsStaff(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

articles/views.py
from django.contrib import messages
from django.shortcuts import render, reverse, redirect

# reset password
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
# ./end reset password 

from django.views.generic import TemplateView, UpdateView, CreateView, DeleteView, DetailView
from django.urls import reverse_lazy
from .forms import SignupAsStaff, ArticleModelForm, CustomCreationForm
from .models import Article
import requests
from newsapp import settings

# reset password
DOMAIN_APP = settings.DOMAIN_APP
SITE_NAME_APP = settings.SITE_NAME_APP
PROTOCOL_APP = settings.PROTOCOL_APP
EMAIL_ADMIN = settings.EMAIL_ADMIN

# News API data
API_URL = settings.API_URL
country = settings.COUNTRY
API_KEY = settings.API_KEY

# validate query parameters
def is_valid_queryparam(param):
    return param != '' and param is not None

# get category
def get_category(request):
    category = request.GET.get('category')
    return (lambda x: category if category else '')(category)

# all news in french
def newsapi_all(request):
    category = get_category(request)
    url = f'{API_URL}={country}&apiKey={API_KEY}&category={category}'
    response = requests.get(url)
    if response.status_code==200:
        data = response.json()
        articles = data['articles']
        return articles

# news by category
def newsapi(request):
    articles = newsapi_all(request)
    return render(request, 'articles/newsapi.html', {'articles': articles})
    
# all articles
def all_articles(request):
    articles = Article.objects.all()
    return articles

# news and articles
def index(request):
    # news api queryset
    news_api = newsapi_all(request)
    # articles queryset
    articles = all_articles(request)
    return render(request, 'articles/index.html', {
                                'news_api': news_api,
                                'articles': articles,
                            })

# articles by category
def articles(request):
    articles = all_articles(request)
    category = request.GET.get('category')
    if (is_valid_queryparam(category)):
        articles = articles.filter(category__contains=category)
    else:
        articles = articles
    return render(request, 'articles/articles.html', {'articles': articles})

# get one article
class ArticleDetailView(DetailView):
    template_name = "articles/single_article.html"
    queryset = Article.objects.all()
    context_object_name = "item"
    
# update the article
class ArticleUpdateView(SignupAsStaff, UpdateView):
    template_name = "articles/update_article.html"
    queryset = Article.objects.all()
    form_class = ArticleModelForm
    success_url = reverse_lazy('articles:index')

# delete article
class ArticleDeleteView(SignupAsStaff, DeleteView):
    template_name = "articles/delete_article.html"
    queryset = Article.objects.all() 
    success_url = reverse_lazy('articles:index')

# create new article
class ArticleCreateView(SignupAsStaff, CreateView):
    model = Article 
    form_class = ArticleModelForm
    template_name = "articles/create_article.html"
    success_url = reverse_lazy('articles:index')

# signup
class SignupView(CreateView):
    form_class = CustomCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy('articles:login')

# about us
class AboutusPageView(TemplateView):
    template_name = "articles/about_us.html"

# reset password
def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users:
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "password/password_reset_email.txt"
                    c = {
                    "email":user.email,
                    'domain': DOMAIN_APP,
                    'site_name': SITE_NAME_APP,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "user": user,
                    'token': default_token_generator.make_token(user),
                    'protocol': PROTOCOL_APP,
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, EMAIL_ADMIN, [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    messages.success(request, 'A message with reset password instructions has been sent to your inbox.')
                    return redirect ("/password_reset/done/")
            else:
                messages.error(request, 'An invalid email has been entered.')
                return redirect("/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="password/password_reset.html", context={"password_reset_form":password_reset_form})

articles/templates/articles/about_us.html
{% extends 'articles/base.html' %}


{% block content %}
    
    <!-- ======= About Section ======= -->
<section id="about" class="about">
  <div class="container">
      
    <div class="row no-gutters">
      <div class="content col-xl-5 d-flex align-items-stretch" data-aos="fade-up">
        <div class="content">
          <h3>Notre mission</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit
          </p>
          <a href="{% url 'articles:index' %}" class="about-btn">Aller aux articles...<i class="bx bx-chevron-right"></i></a>
        </div>
      </div>
      <div class="col-xl-7 d-flex align-items-stretch">
        <div class="icon-boxes d-flex flex-column justify-content-center">
          <div class="row">
            <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
              <i class="bx bx-receipt"></i>
              <h4>Corporis voluptates sit</h4>
              <p>Consequuntur sunt aut quasi enim aliquam quae harum pariatur laboris nisi ut aliquip</p>
            </div>
            <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
              <i class="bx bx-cube-alt"></i>
              <h4>Ullamco laboris nisi</h4>
              <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt</p>
            </div>
            <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
              <i class="bx bx-images"></i>
              <h4>Labore consequatur</h4>
              <p>Aut suscipit aut cum nemo deleniti aut omnis. Doloribus ut maiores omnis facere</p>
            </div>
            <div class="col-md-6 icon-box" data-aos="fade-up" data-aos-delay="400">
              <i class="bx bx-shield"></i>
              <h4>Beatae veritatis</h4>
              <p>Expedita veritatis consequuntur nihil tempore laudantium vitae denat pacta</p>
            </div>
          </div>
        </div><!-- End .content-->
      </div>
    </div>

  </div>
</section>
<!-- End About Section -->
{% endblock content %}


    

articles/templates/articles/articles.html
{% extends "articles/base.html" %}

<!-- static files -->
{% load static %}

<!-- content -->
{% block content %}

<!-- Messages Section -->
{% include "articles/messages.html" %}

<!-- ======= Content Section ======= -->
<section id="testimonials" class="testimonials section-bg">
  <div class="container">
    <div class="row">
      {% for item in articles %}
      <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">
        <div class="testimonial-item">
          <img
            src="{{ item.authors_image_url }}"
            class="testimonial-img"
            alt="auth-img"
          />
          <h3>{{ item.title }}</h3>
          {{ item.authors }}
          <small class="text-muted">{{item.created_at}}</small>
          <br />
          <!-- <i class="bx bxs-quote-alt-left quote-icon-left"></i> -->
          {{ item.content | truncatewords_html:55 }}
          <a
            href="{% url 'articles:single_article' item.slug %}"
            class="btn btn-outline-secondary"
            >Lire la suite</a
          >
          <!-- <i class="bx bxs-quote-alt-right quote-icon-right"></i> -->
        </div>
      </div>
      {% empty %}
      <p>Il n'y a pas d'articles</p>

      {% endfor %}
    </div>
  </div>
</section>
<!-- End Content Section -->

<!-- ======= Cta Section ======= -->
<section id="cta" class="cta">
  <div class="container" data-aos="zoom-in">
    <div class="text-center">
      <h3>Appel à l'Action</h3>
      <p>
        Si vous souhaitez être informé ou souhaitez exprimer votre opinion,
        veuillez nous contacter.
      </p>
      <a class="cta-btn" href="#">Appel à l'Action</a>
    </div>
  </div>
</section>
<!-- End Cta Section -->

<!-- ======= Slide Content Section ======= -->
<section id="testimonials" class="testimonials section-bg">
  <div class="container">
    <div class="section-title" data-aos="fade-in" data-aos-delay="100">
      <h2>Tous les articles</h2>
      <p>
        Vous trouverez ici une série d'articles sur divers sujets, tels que la
        littérature, les arts, la politique, la santé, la science, le sport,
        l'actualité, etc.
      </p>
    </div>

    <div
      class="testimonials-slider swiper-container"
      data-aos="fade-up"
      data-aos-delay="100"
    >
      <div class="swiper-wrapper">
        {% for item in articles %}
        <!-- Slide Articles Content Item -->
        <div class="swiper-slide">
          <div class="testimonial-item">
            <img
              src=" {{ item.authors_image_url }} "
              class="testimonial-img"
              alt="content-img"
            />

            <h3>{{ item.title }}</h3>
            {{ item.authors }}
            <br />
            <small class="text-muted">{{item.created_at}}</small>
            <p>
              <!-- <i class="bx bxs-quote-alt-left quote-icon-left"></i> -->
              {{ item.content | truncatewords_html:25 }}
              <a
                href="{% url 'articles:single_article' item.slug %}"
                class="btn btn-outline-secondary"
                >Lire la suite</a
              >
              <!-- <i class="bx bxs-quote-alt-right quote-icon-right"></i> -->
            </p>
          </div>
        </div>
        {% empty %}
        <p>Il n'y a pas d'articles</p>
        <!-- End content item -->
        {% endfor %}
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>
</section>
<!-- End Slide Content Section -->

{% endblock content %}

articles/templates/articles/create_article.html
{% extends "articles/base.html" %}

<!-- static files -->
{% load static %}

<!-- content -->
{% block content %}

<!-- crispy forms -->
{%load crispy_forms_tags %}
<h3>Créer un nouvel article</h3>
<hr />
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- form -->
        {{ form|crispy }}
        <hr />
        <input type="submit" value="Soumettre" class="btn btn-success" />
      </form>
    </div>
  </div>
</div>

<script src="{% static 'js/slugify.js' %}"></script>
{% endblock %}

articles/templates/articles/delete_article.html
{% extends "articles/base.html" %}

<!-- static files -->
{% load static %}

<!-- content -->
{% block content %}
<br />
<br />
{%load crispy_forms_tags %}
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <h3 style="background-color: rgba(255, 0, 0, 0.733)">
        Supprimer cet article ? Es-tu sûr?
      </h3>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- form -->
        {{ form|crispy }}
        <a href="{% url 'articles:index' %}" type="button" class="btn btn-info">
          Annuler
        </a>
        <button type="submit" value="submit" class="btn btn-danger">
          Soumettre
        </button>
        <hr />
      </form>
    </div>
  </div>
</div>

{% endblock %}

articles/templates/articles/header.html
<!-- ======= Header ======= -->
<header id="header" class="fixed-top header-transparent">
  <div class="container d-flex align-items-center justify-content-between">
    <div class="logo">
      <h1 class="text-light">
        <a href="{% url 'articles:index' %}"><span>On parle francais</span></a>
      </h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
    </div>

    <nav id="navbar" class="navbar">
      <ul>
        <li>
          <a class="nav-link scrollto" href="{% url 'articles:about_us' %}"
            >Pour Nous</a
          >
        </li>
        <li>
          <a class="nav-link scrollto" href="{% url 'articles:index' %}"
            >Tous</a
          >
        </li>

        <li class="dropdown">
          <a href="#"
            ><span>Articles</span> <i class="bi bi-chevron-right"></i
          ></a>
          <ul>
            <li><a href="{% url 'articles:articles' %}">Tous</a></li>
            <li>
              <a href="{% url 'articles:articles' %}?category=ACT">Actualité</a>
            </li>
            <li>
              <a href="{% url 'articles:articles' %}?category=BNS">Économie</a>
            </li>
            <li>
              <a href="{% url 'articles:articles' %}?category=POL">Politique</a>
            </li>
            <li>
              <a href="{% url 'articles:articles' %}?category=HL">Santé</a>
            </li>
            <li>
              <a href="{% url 'articles:articles' %}?category=HS">Histoire</a>
            </li>
            <li>
              <a href="{% url 'articles:articles' %}?category=LTR"
                >Littérature</a
              >
            </li>
            <li>
              <a href="{% url 'articles:articles' %}?category=ENTM"
                >Divertissement</a
              >
            </li>
            <li>
              <a href="{% url 'articles:articles' %}?category=SP">Sport</a>
            </li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#"
            ><span>Journaux</span> <i class="bi bi-chevron-right"></i
          ></a>
          <ul>
            <li><a href="{% url 'articles:newsapi' %}">Tous</a></li>
            <li>
              <a href="{% url 'articles:newsapi' %}?category=health">Santé</a>
            </li>
            <li>
              <a href="{% url 'articles:newsapi' %}?category=technology"
                >Technologie</a
              >
            </li>
            <li>
              <a href="{% url 'articles:newsapi' %}?category=Entertainment"
                >Divertissement</a
              >
            </li>
            <li>
              <a href="{% url 'articles:newsapi' %}?category=Business"
                >Économique</a
              >
            </li>
            <li>
              <a href="{% url 'articles:newsapi' %}?category=Sports">Sports</a>
            </li>
            <li>
              <a href="{% url 'articles:newsapi' %}?category=Science"
                >Science</a
              >
            </li>
          </ul>
        </li>
        <li><a class="nav-link scrollto" href="#contact">Nous Contacter</a></li>
        {% if not request.user.is_authenticated %}
        <li>
          <a class="nav-link scrollto" href=" {% url 'articles:signup' %} "
            >Signup</a
          >
        </li>

        {% endif %}

        <!-- staff member -->
        {% if request.user.is_staff %}
        <li>
          <a
            class="nav-link scrollto"
            href=" {% url 'articles:create_article' %} "
            >Créer Article</a
          >
        </li>
        {% endif %}

        <!-- authentication -->
        {% if request.user.is_authenticated %}
        <li class="nav-link scrollto">
          <span style="color: cornsilk">{{ request.user.username }}</span>
        </li>

        <li>
          <a class="nav-link scrollto" href=" {% url 'articles:logout' %} "
            >Logout</a
          >
        </li>
        {% else %}
        <li>
          <a class="nav-link scrollto" href=" {% url 'articles:login' %} "
            >Login</a
          >
        </li>
        {% endif %}
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav>
    <!-- .navbar -->
  </div>
</header>
<!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero">
  <div class="hero-container" data-aos="fade-up">
    <h1>Bienvenue sur notre page</h1>
    <h2>
      A travers ce site, vous pouvez donner votre avis et vous pouvez trouver
      des actualités dans tous les domaines
    </h2>
    <a href="{% url 'articles:index' %}" class="btn-get-started scrollto"
      ><i class="bx bx-chevrons-down"></i
    ></a>
  </div>
</section>
<!-- End Hero -->

articles/templates/articles/index.html
{% extends "articles/base.html" %}

<!-- static files -->
{% load static %}

<!-- content -->
{% block content %}    

<!-- Messages Section -->
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<!-- ======= Content Section ======= -->
<section id="testimonials" class="testimonials section-bg">
    <div class="container">            
        <div class="row">
            <div class="col-md-9">
                <div class="container-lg container-md container-sm">
                    <h3>Journaux</h3>
                    <div class="row">
                        {% for i in news_api %}
                            <div class="col-lg-6 col-md-12 col-sm-12">
                                <div class="card rounded shadow-lg m-2" style="width: 25rem;">
                                    <img src="{{ i.urlToImage }}" class="card-img-top" alt="{{ i.title }}" >
                                    <div class="card-body">
                                        <p class="card-text">{{ i.author }}</p>
                                        <h5 class="card-title">{{ i.title }}</h5>
                                        <p class="card-title">{{ i.source.name }}</p>
                                        <p class="card-text">{{ i.description }}</p>
                                        <a href="{{ i.url }}" target="_blank" class="btn btn-outline-secondary">Lire la suite</a>
                                        <small>date: {{ i.publishedAt }}</small>
                                    </div>
                                </div>
                            </div>
                            {% empty %}
                            <p>Il n'y a pas de nouvelles</p>
                        {% endfor %}
                    </div>
                </div>                   
            </div>
            <!-- Articles -->
            <div class="col-md-3">                    
                <div class="container">
                    <h3>Articles</h3>
                    <div class="row">
                        {% for item in articles %}
                        <div class="col-lg-12 col-md-12 col-sm-12" data-aos="fade-up" data-aos-delay="100">
                            <div class="testimonial-item">
                                <img src="{{ item.authors_image_url }}" class="testimonial-img" alt="auth-img">
                                <h3>{{ item.title }}</h3>
                                {{ item.authors }}
                                <small class="text-muted">{{item.created_at}}</small>
                                <br>
                                    <!-- <i class="bx bxs-quote-alt-left quote-icon-left"></i> -->
                                        {{ item.content | truncatewords_html:55 }}
                                        <a href="{% url 'articles:single_article' item.slug %}" class="btn btn-outline-secondary">Lire la suite</a>
                                    <!-- <i class="bx bxs-quote-alt-right quote-icon-right"></i> -->
                            </div>
                        </div>
                        <hr>
                            {% empty %}
                                <p>Il n'y a pas d'articles</p>
                        {% endfor %}                            
                    </div>
                </div>                        
            </div>                
        </div>    
    </div>
</section><!-- End Content Section -->


<!-- ======= Cta Section ======= -->
<section id="cta" class="cta">
    <div class="container" data-aos="zoom-in">
        
        <div class="text-center">
            <h3>Appel à l'Action</h3>
            <p>Si vous souhaitez être informé ou souhaitez exprimer votre opinion, veuillez nous contacter.</p>
            <a class="cta-btn" href="#">Appel à l'Action</a>
        </div>
        
    </div>
</section><!-- End Cta Section -->

<!-- ======= Slide Content Section ======= -->
<section id="testimonials" class="testimonials section-bg">
    <div class="container">
        
        <div class="section-title" data-aos="fade-in" data-aos-delay="100">
            <h2>Tous les articles</h2>
            <p>Vous trouverez ici une série d'articles sur divers sujets, tels que la littérature, les arts, la politique, la santé, la science, le sport, l'actualité, etc.</p>
        </div>
        
        <div class="testimonials-slider swiper-container" data-aos="fade-up" data-aos-delay="100">
            <div class="swiper-wrapper">
                
                {% for item in articles %}
                    <!-- Slide Articles Content Item -->
                <div class="swiper-slide">
                    <div class="testimonial-item">
                        <img src= " {{ item.authors_image_url }} " class="testimonial-img" alt="content-img">

                        <h3>{{ item.title }}</h3>
                        {{ item.authors }}
                        <br>
                        <small class="text-muted">{{item.created_at}}</small>
                        <p>
                            <!-- <i class="bx bxs-quote-alt-left quote-icon-left"></i> -->
                                {{ item.content | truncatewords_html:25 }}
                                <a href="{% url 'articles:single_article' item.slug %}" class="btn btn-outline-secondary">Lire la suite</a>
                                <!-- <i class="bx bxs-quote-alt-right quote-icon-right"></i> -->
                        </p>
                    </div>
                </div><!-- End content item -->
                {% endfor %}
            </div>
            <div class="swiper-pagination"></div>
        </div>
    
    </div>
</section><!-- End Slide Content Section -->



{% endblock content %}

articles/templates/articles/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    {% comment %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {% endcomment %}
    <!-- alert message -->
    {{ message }}
  </div>
</div>
{% endfor %}

articles/templates/articles/single_article.html
{% extends 'articles/base.html' %} 

<!-- static files -->
{% load static %} 

<!-- content -->
{% block content %}
<!-- ======= Content Section ======= -->
<section id="testimonials" class="testimonials section-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12" data-aos="fade-up" data-aos-delay="100">
        <div class="testimonial-item">
          <img
            src="{{ item.authors_image_url }}"
            class="testimonial-img"
            alt=""
          />
          <img
            src="{{ item.content_image_url }}"
            class="testimonial-content-img"
            alt="content-img"
          />
          <h3>{{ item.title }}</h3>
          {{ item.authors }}
          <br />
          <small class="text-muted">{{item.created_at}}</small>
          <br />
          {{ item.content }}
        </div>
        <hr />
        {% if request.user.is_authenticated and request.user.is_staff %}
        
        <div>
          <a
          href="{% url 'articles:index' %}"
          type="button"
          class="button btn btn-info"
          >Tous Articles</a
          >
          <a
            href="{% url 'articles:update_article' item.slug %}"
            type="button"
            class="button btn btn-warning"
            >Modifier</a
          >
          <a
            href="{% url 'articles:delete_article' item.slug %}"
            type="button"
            class="btn btn-danger"
          >
            Effacer
          </a>
        {% endif %}
      </div>
    </div>
  </div>
</section>
<!-- End Content Section -->

{% endblock content %}

articles/templates/articles/update_article.html
{% extends "articles/base.html" %}

<!-- static files -->
{% load static %}

<!-- content -->
{% block content %}

<h3>Modifier cet article</h3>
<hr />
{%load crispy_forms_tags %}
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- form -->
        {{ form|crispy }}
        <hr />
        <a
          href=" {% url 'articles:index' %} "
          type="button"
          class="btn btn-info"
          >Annuler</a
        >
        <input type="submit" value="Soumettre" class="btn btn-warning" />
      </form>
    </div>
  </div>
</div>

<script src="{% static 'js/slugify.js' %}"></script>
{% endblock %}